name: OnTheQuest
version: '${version}'
main: xyz.bluspring.onthequest.OnTheQuest
api-version: 1.19
authors: [ BluSpring ]
description: Custom plugin made for the Quest SMP.
website: https://bluspring.xyz
commands:
  jewel-random:
    permission: otq.admin
permissions:
  otq.admin:
    description: OnTheQuest Admin
    default: op